### ISSUE TITLE
the example takes 15+ minutes to run

### ISSUE THREAD

**Issue by strixcuriosus** [barentsen/planetpixel#1]
The current implementation involves creating an order, polling for completion, and downloading results.

Consider using [tile services](https://developers.planet.com/docs/api/tile-services/) instead.

This Hack Day example notebook renders tiles over time for a specified lat, lon, and time range: https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/webtiles/visualize_imagery_over_time.ipynb

**Comment by barentsen** [comment]
Confirmed: it takes very long to get clipped data from the orders API!

My understanding is that it's not appropriate to use the tile service for scientific/analytical analysis of the data. Is that incorrect?

**Comment by strixcuriosus** [comment]
It is correct that for many scientific analysis applications the approach you are taking to get the `PSScene4Band` pixels will be more appropriate.

For use cases such as "looking for your favorite lake freezing" the webtile images may suffice.

**Comment by barentsen** [comment]
Thanks for your feedback @strixcuriosus!  I intended the "lake freezing" example to demonstrate how to scientifically analyze a small patch of Earth, hence the use of the `PSScene4Band` pixels. 

It's a shame there's no fast way to retrieve science-grade data for small patches of land yet!
